In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("GSM4089151_P1_gene_cell_exprs_table.txt")

In [3]:
df   #FILE WAS NOT CSV

      Gene_ID\tSymbol\tAAACCTGAGAGCTATA.1\tAAACCTGAGTGTTTGC.1\tAAACCTGCAGTCAGCC.1\tAAACCTGGTACATGTC.1\tAAACCTGGTCGGCATC.1\tAAACCTGGTGCAGACA.1\tAAACCTGTCATTCACT.1\tAAACCTGTCTTGAGGT.1\tAAACGGGAGAGCCTAG.1\tAAACGGGCAATAAGCA.1\tAAACGGGGTAGGCATG.1\tAAACGGGGTCGACTAT.1\tAAACGGGGTCGATTGT.1\tAAACGGGTCAGCTTAG.1\tAAAGATGAGACCTTTG.1\tAAAGATGCACCAGATT.1\tAAAGATGGTAGCGTGA.1\tAAAGATGGTTACCAGT.1\tAAAGATGTCGACCAGC.1\tAAAGCAAAGACTACAA.1\tAAAGCAAAGAGGTAGA.1\tAAAGCAAAGCTATGCT.1\tAAAGCAACACCGGAAA.1\tAAAGCAATCGCTAGCG.1\tAAAGCAATCTCAACTT.1\tAAAGCAATCTCTTATG.1\tAAAGTAGAGACTAGGC.1\tAAAGTAGAGCTGAAAT.1\tAAAGTAGAGCTGCCCA.1\tAAAGTAGCATCTCGCT.1\tAAAGTAGGTCACCCAG.1\tAAAGTAGGTCCGTCAG.1\tAAAGTAGGTTGGACCC.1\tAAAGTAGTCATAGCAC.1\tAAAGTAGTCCACGTTC.1\tAAAGTAGTCGTTTATC.1\tAAATGCCAGCCCAACC.1\tAAATGCCAGGATCGCA.1\tAAATGCCAGGCAGTCA.1\tAAATGCCCATCCGGGT.1\tAAATGCCCATCGACGC.1\tAAATGCCGTACAAGTA.1\tAAATGCCGTCCTAGCG.1\tAAATGCCGTTCAGACT.1\tAAATGCCTCGCTTAGA.1\tAACACGTAGCAGACTG.1\tAACACGTCAAGGGTCA.1\tAACACGTCACACTGCG.1\tAACACGTCAGATAATG.1\tAACACGTCAGTACACT.1\tAACACGTTCACTATTC.1\tAACACGTTCATTTGGG.1\tAACACGTTCCTTTCGG.1\tAACCATGAGAAACCTA.1\tAACCATGAGTCACGCC.1\tAACCATGCAATGGAAT.1\tAACCATGGTCCCGACA.1\tAACCGCGAGAACTGTA.1\tAACCGCGAGACTAGGC.1\tAACCGCGAGCAATATG.1\tAACCGCGCAAGCGATG.1\tAACCGCGCACCAGGTC.1\tAACCGCGCACGAAGCA.1\tAACCGCGCATCGACGC.1\tAACCGCGGTACCATCA.1\tAACCGCGGTCGCGAAA.1\tAACCGCGGTCGGCTCA.1\tAACCGCGTCCAAACAC.1\tAACCGCGTCCTTTCTC.1\tAACGTTGAGTTAAGTG.1\tAACGTTGCAAGACGTG.1\tAACGTTGGTAGGACAC.1\tAACGTTGTCGGATGGA.1\tAACGTTGTCGGTGTCG.1\tAACTCAGAGACGCACA.1\tAACTCAGAGGACAGAA.1\tAACTCAGAGTTGTCGT.1\tAACTCAGCAAAGTCAA.1\tAACTCAGCAATGGAAT.1\tAACTCAGCACGAAAGC.1\tAACTCAGCAGATTGCT.1\tAACTCAGCAGCCACCA.1\tAACTCAGGTAAGTGGC.1\tAACTCAGGTAGAGTGC.1\tAACTCAGGTTGACGTT.1\tAACTCAGTCACCGTAA.1\tAACTCCCAGTACATGA.1\tAACTCCCCAAGAGTCG.1\tAACTCCCCAGGAACGT.1\tAACTCCCCATTGGGCC.1\tAACTCCCGTCGACTAT.1\tAACTCCCGTCGCTTCT.1\tAACTCCCGTCTGCGGT.1\tAACTCCCGTTCTGTTT.1\tAACTCCCTCAATCTCT.1\tAACTCTTAGACCACGA.1\tAACTCTTAGAGGACGG.1\tAACTCTTAGCTGTTCA.1\tAACTCTTAGGGCTTCC.1\tAACTCTTCACAGGCCT.1\tAACTCTTCACCAGGTC.1\tAACTCTTCACCGATAT.1\tAACTCTTCAGCCAATT.1\tAACTGGTCACAAGTAA.1\tAACTGGTCATTCACTT.1\tAACTGGTGTGCCTTGG.1\tAACTGGTGTTAGATGA.1\tAACTGGTTCATGCTCC.1\tAACTGGTTCCCAAGTA.1\tAACTGGTTCCTCATTA.1\tAACTGGTTCGATGAGG.1\tAACTTTCAGAACTGTA.1\tAACTTTCAGATAGCAT.1\tAACTTTCAGGTACTCT.1\tAACTTTCAGTACGCGA.1\tAACTTTCAGTCACGCC.1\tAACTTTCAGTGGACGT.1\tAACTTTCAGTGGGATC.1\tAACTTTCCAAGAAAGG.1\tAACTTTCCATGCAACT.1\tAACTTTCGTCCCTACT.1\tAACTTTCGTGTGAAAT.1\tAACTTTCTCACATACG.1\tAAGACCTAGCTACCTA.1\tAAGACCTCAATCACAC.1\tAAGACCTCAATTCCTT.1\tAAGACCTCACCGATAT.1\tAAGACCTCATTACCTT.1\tAAGACCTGTAAACACA.1\tAAGACCTTCATTGCCC.1\tAAGACCTTCTAAGCCA.1\tAAGCCGCAGGAGTCTG.1\tAAGCCGCAGTGACATA.1\tAAGCCGCCAAGCCATT.1\tAAGCCGCGTATCTGCA.1\tAAGCCGCGTGCTTCTC.1\tAAGCCGCGTGTGACCC.1\tAAGCCGCGTTTAAGCC.1\tAAGCCGCTCAAGGCTT.1\tAAGCCGCTCACAAACC.1\tAAGCCGCTCGCGGATC.1\tAAGGAGCAGGCGACAT.1\tAAGGAGCAGTTGTAGA.1\tAAGGAGCCAAGTCTGT.1\tAAGGAGCCACTACAGT.1\tAAGGAGCCATATACCG.1\tAAGGAGCGTATAGTAG.1\tAAGGAGCGTGTTGAGG.1\tAAGGAGCGTTCGTGAT.1\tAAGGCAGAGGAATTAC.1\tAAGGCAGCACATCTTT.1\tAAGGCAGCAGACTCGC.1\tAAGGCAGCAGCTGTGC.1\tAAGGCAGCATCACGAT.1\tAAGGCAGGTTGCTCCT.1\tAAGGCAGTCACAGGCC.1\tAAGGCAGTCTCATTCA.1\tAAGGTTCAGAACAATC.1\tAAGGTTCAGAAGAAGC.1\tAAGGTTCCAAGCTGAG.1\tAAGGTTCCACATTAGC.1\tAAGGTTCGTAATCGTC.1\tAAGGTTCTCATGCTCC.1\tAAGGTTCTCGCAAACT.1\tAAGTCTGAGACAGACC.1\tAAGTCTGAGGAGTACC.1\tAAGTCTGAGGTGCTTT.1\tAAGTCTGCATGAACCT.1\tAAGTCTGGTCTAGTGT.1\tAAGTCTGTCAGCGACC.1\tAAGTCTGTCCACGTGG.1\tAAGTCTGTCCAGTATG.1\tAATCCAGAGGCAGTCA.1\tAATCCAGCAGCCTTGG.1\tAATCCAGGTGCGATAG.1\tAATCCAGGTGCTTCTC.1\tAATCCAGTCTGAAAGA.1\tAATCGGTAGATGGGTC.1\tAATCGGTCAAGAAGAG.1\tAATCGGTCAGGCAGTA.1\tAATCGGTCATGGAATA.1\tAATCGGTGTAGCGTCC.1\tAATCGGTGTCAAGCGA.1\tAATCGGTGTCGGCACT.1\tAATCGGTGTCTGATCA.1\tAATCGGTTCAGAGGTG.1\tAATCGGTTCCTTCAAT.1\tAATCGGTTCTTTCCTC.1\tACACCAAAGACCGGAT.1\tACACCAAAGAGGGCTT.1\tACACCAAAGCGTAGTG.1\tACACCAAAGCTACCGC.1\tACACCAAAGCTTCGCG.1\tACACCAAAGTAGGTGC.1\tACACCAAGTACATGTC.1\tACACCAAGTCTACCTC.1\tACACCAAGTGCAACGA.1\tACACCAAGTTGATTCG.1\tACACCAAGTTGTGGCC.1\tACACCAATCTCATTCA.1\tACACCCTAGTGGCACA.1\tACACCCTCAAAGGCGT.1\tACACCCTCACACAGAG.1\tACACCCTCAGACGTAG.1\tACACCGGAGATCCCGC.1\tACACCGGAGGGAACGG.1\tACACCGGCACATTTCT.1\tACACCGGCAGGGAGAG.1\tACACCGGGTCCGTCAG.1\tACACCGGGTGTAACGG.1\tACACCGGTCAATCACG.1\tACACCGGTCCACGCAG.1\tACACCGGTCGGCTACG.1\tACACCGGTCTGGGCCA.1\tACACTGAAGAATAGGG.1\tACACTGAAGCAGGTCA.1\tACACTGAAGCGCCTCA.1\tACACTGAAGGCTAGGT.1\tACACTGACAATGGACG.1\tACACTGACAATTGCTG.1\tACACTGACAGTTCATG.1\tACACTGAGTAAGTGTA.1\tACACTGAGTGTGAATA.1\tACACTGATCACAAACC.1\tACACTGATCGCAAGCC.1\tACACTGATCGCAGGCT.1\tACACTGATCTATGTGG.1\tACACTGATCTGTACGA.1\tACAGCCGAGACATAAC.1\tACAGCCGAGCCACGTC.1\tACAGCCGAGCTGCAAG.1\tACAGCCGCATATGGTC.1\tACAGCCGGTATAGGGC.1\tACAGCCGTCGCCAGCA.1\tACAGCCGTCGCGCCAA.1\tACAGCTAAGGCACATG.1\tACAGCTACAGGACGTA.1\tACAGCTACATGTAGTC.1\tACAGCTAGTCACTTCC.1\tACAGCTATCTTGTATC.1\tACATACGAGAGGTAGA.1\tACATACGAGATGCCTT.1\tACATACGAGCCAGTTT.1\tACATACGAGCTAACAA.1\tACATACGCAATCCGAT.1\tACATACGCATCACCCT.1\tACATACGTCCTGCAGG.1\tACATACGTCTGGAGCC.1\tACATCAGAGCAGCGTA.1\tACATCAGAGGGCTTGA.1\tACATCAGCAATGCCAT.1\tACATCAGGTCCAGTGC.1\tACATCAGGTGCAGACA.1\tACATCAGTCACTCTTA.1\tACATCAGTCATGTCTT.1\tACATCAGTCCACTCCA.1\tACATCAGTCTAACCGA.1\tACATGGTAGGCCCTCA.1\tACATGGTAGTCATCCA.1\tACATGGTAGTCCATAC.1\tACATGGTCAACAACCT.1\tACATGGTGTAGCGCAA.1\tACATGGTTCACGATGT.1\tACCAGTAAGCTACCGC.1\tACCAGTAAGCTTATCG.1\tACCAGTAAGGACAGAA.1\tACCAGTACAATCCGAT.1\tACCAGTACACCTCGTT.1\tACCAGTACATCCGTGG.1\tACCAGTACATGGGACA.1\tACCAGTAGTGTGTGCC.1\tACCAGTATCAATAAGG.1\tACCAGTATCTTCCTTC.1\tACCCACTAGGGTATCG.1\tACCCACTAGTCTTGCA.1\tACCCACTCAAAGAATC.1\tACCCACTCACGAAGCA.1\tACCCACTCACTCGACG.1\tACCCACTGTATTCGTG.1\tACCCACTGTGTATGGG.1\tACCCACTTCAACGAAA.1\tACCGTAACACAACGTT.1\tACCGTAACATTATCTC.1\tACCGTAAGTCAAACTC.1\tACCGTAATCGCAAACT.1\tACCGTAATCTGTCCGT.1\tACCGTAATCTTCAACT.1\tACCGTAATCTTGCCGT.1\tACCTTTAAGGCTAGAC.1\tACCTTTACAAAGAATC.1\tACCTTTACACAACTGT.1\tACCTTTACACAGACAG.1\tACCTTTACAGTCGATT.1\tACCTTTACATTGTGCA.1\tACCTTTAGTATTACCG.1\tACCTTTAGTCACAAGG.1\tACCTTTAGTGGACGAT.1\tACCTTTATCAGTTCGA.1\tACGAGCCAGAAACGAG.1\tACGAGCCAGATGTCGG.1\tACGAGCCAGGTAAACT.1\tACGAGCCCAACACGCC.1\tACGAGCCCAATAGCAA.1\tACGAGCCCACAAGTAA.1\tACGAGCCGTCAAAGCG.1\tACGAGCCTCATGCTCC.1\tACGAGCCTCCAGAAGG.1\tACGAGGACACCCAGTG.1\tACGAGGACACTCAGGC.1\tACGAGGACATATACCG.1\tACGAGGAGTAGCCTAT.1\tACGAGGAGTATATCCG.1\tACGAGGAGTATCAGTC.1\tACGAGGATCAAACGGG.1\tACGAGGATCAATCTCT.1\tACGAGGATCAGTGTTG.1\tACGAGGATCATAGCAC.1\tACGAGGATCGCGTAGC.1\tACGAGGATCGTGTAGT.1\tACGAGGATCTGCGTAA.1\tACGAGGATCTGCTTGC.1\tACGATACAGCCGATTT.1\tACGATACAGGGATGGG.1\tACGATACCAATGTAAG.1\tACGATACCACGAGAGT.1\tACGATACCACGGTAAG.1\tACGATACCAGATGAGC.1\tACGATACCATGTCGAT.1\tACGATACGTGATGTCT.1\tACGATACTCAAACGGG.1\tACGATACTCCAGTATG.1\tACGATACTCTTATCTG.1\tACGATGTAGCCTATGT.1\tACGATGTCAAGCTGTT.1\tACGATGTGTAAGTAGT.1\tACGATGTGTAGCGTAG.1\tACGATGTGTCGAATCT.1\tACGATGTGTCTGCAAT.1\tACGATGTTCATACGGT.1\tACGCAGCAGGCTAGCA.1\tACGCAGCCACACCGAC.1\tACGCAGCCAGCCTGTG.1\tACGCAGCCAGTCAGAG.1\tACGCAGCCATCACGTA.1\tACGCAGCGTGTAAGTA.1\tACGCAGCTCTCGGACG.1\tACGCCAGAGCGCTTAT.1\tACGCCAGCACTGAAGG.1\tACGCCAGTCACTTCAT.1\tACGCCAGTCAGTGTTG.1\tACGCCAGTCCAAACTG.1\tACGCCAGTCCCACTTG.1\tACGCCGAAGAGTACCG.1\tACGCCGACAAATCCGT.1\tACGCCGACACATAACC.1\tACGCCGACAGGCGATA.1\tACGCCGACAGGTTTCA.1\tACGCCGACATACCATG.1\tACGCCGACATGTAGTC.1\tACGCCGAGTCGGCATC.1\tACGCCGAGTCTTGATG.1\tACGCCGAGTTGATTGC.1\tACGCCGATCATGGTCA.1\tACGCCGATCGTTGCCT.1\tACGCCGATCTGGCGAC.1\tACGGAGAAGCGATATA.1\tACGGAGAAGCTATGCT.1\tACGGAGAAGTGATCGG.1\tACGGAGACACAACTGT.1\tACGGAGACAGTTCATG.1\tACGGAGACATGACATC.1\tACGGAGAGTCAGAAGC.1\tACGGAGAGTCCGTGAC.1\tACGGAGATCACATAGC.1\tACGGAGATCATTATCC.1\tACGGAGATCCATTCTA.1\tACGGAGATCGGAATCT.1\tACGGCCAAGGCTCTTA.1\tACGGCCAAGGTAGCTG.1\tACGGCCACAACAACCT.1\tACGGCCACACAACGCC.1\tACGGCCACATGCCTTC.1\tACGGCCAGTACCGAGA.1\tACGGCCAGTTAAAGAC.1\tACGGCCATCGGGAGTA.1\tACGGGCTAGTACGATA.1\tACGGGCTTCCGCAAGC.1\tACGGGCTTCTTCAACT.1\tACGGGTCCACGACTCG.1\tACGGGTCCACTCGACG.1\tACGGGTCGTATGAAAC.1\tACGGGTCGTCTAAACC.1\tACGGGTCTCGAGCCCA.1\tACGTCAAAGTGAAGTT.1\tACGTCAACACACATGT.1\tACGTCAACACCGCTAG.1\tACGTCAATCCAGATCA.1\tACGTCAATCCTCTAGC.1\tACGTCAATCTATGTGG.1\tACTATCTAGTATCGAA.1\tACTATCTAGTTACGGG.1\tACTATCTCAATGACCT.1\tACTATCTCAGGATCGA.1\tACTATCTGTCCGAGTC.1\tACTATCTGTCGGCACT.1\tACTATCTGTTCCATGA.1\tACTATCTTCAATCTCT.1\tACTATCTTCCGCTGTT.1\tACTATCTTCGCCAAAT.1\tACTATCTTCGTTGCCT.1\tACTGAACAGGTGCTTT.1\tACTGAACAGTACATGA.1\tACTGAACGTGTGAAAT.1\tACTGAACTCCCATTTA.1\tACTGAACTCCTTCAAT.1\tACTGAACTCTACCAGA.1\tACTGAACTCTGCAGTA.1\tACTGAGTAGTAATCCC.1\tACTGAGTCACTGTCGG.1\tACTGAGTGTCCGAACC.1\tACTGAGTGTGGTAACG.1\tACTGAGTGTTTACTCT.1\tACTGAGTTCAACGGCC.1\tACTGAGTTCACTTCAT.1\tACTGAGTTCCGGGTGT.1\tACTGAGTTCTGCTGCT.1\tACTGATGAGAGAACAG.1\tACTGATGCAAGTTAAG.1\tACTGATGCACATCTTT.1\tACTGATGTCCGAACGC.1\tACTGCTCAGAAGGTGA.1\tACTGCTCAGATCTGAA.1\tACTGCTCAGCAACGGT.1\tACTGCTCAGGGTCGAT.1\tACTGCTCCAAGCCGTC.1\tACTGCTCGTACATCCA.1\tACTGCTCGTAGCGCTC.1\tACTGCTCGTCTAGCGC.1\tACTGCTCTCGGCGCTA.1\tACTGCTCTCGTAGGTT.1\tACTGTCCCAAACCTAC.1\tACTGTCCCATGGTAGG.1\tACTGTCCGTAAGGGAA.1\tACTGTCCTCGAGGTAG.1\tACTGTCCTCGGCATCG.1\tACTGTCCTCGGTTCGG.1\tACTTACTAGCTAAACA.1\tACTTACTAGCTACCGC.1\tACTTACTAGGACACCA.1\tACTTACTAGTGGTCCC.1\tACTTACTTCAACACAC.1\tACTTACTTCGCTTAGA.1\tACTTGTTAGAAGGTTT.1\tACTTGTTAGAGTACCG.1\tACTTGTTAGATACACA.1\tACTTGTTAGCGTCAAG.1\tACTTGTTAGGCGTACA.1\tACTTGTTAGTACGTAA.1\tACTTGTTCACACAGAG.1\tACTTGTTCACTAGTAC.1\tACTTGTTCAGTCTTCC.1\tACTTGTTGTAAATGAC.1\tACTTGTTGTATGCTTG.1\tACTTGTTGTCACTGGC.1\tACTTGTTGTCTAACGT.1\tACTTGTTGTTCGTCTC.1\tACTTGTTTCACTCCTG.1\tACTTGTTTCCGAGCCA.1\tACTTGTTTCTTGTTTG.1\tACTTTCACACAACGCC.1\tACTTTCAGTAACGTTC.1\tACTTTCAGTCCCTTGT.1\tACTTTCATCAGAGCTT.1\tACTTTCATCCTTGCCA.1\tACTTTCATCGTGTAGT.1\tAGAATAGAGAGGGCTT.1\tAGAATAGAGAGGTTAT.1\tAGAATAGCATATACGC.1\tAGAATAGGTGGTTTCA.1\tAGAATAGTCAGAGACG.1\tAGACGTTAGCTACCTA.1\tAGACGTTAGGTAAACT.1\tAGACGTTAGTCAATAG.1\tAGACGTTGTGAGGGAG.1\tAGACGTTGTTGTACAC.1\tAGACGTTGTTTCCACC.1\tAGACGTTTCACGCGGT.1\tAGACGTTTCATCGATG.1\tAGACGTTTCGGTTAAC.1\tAGAGCGAAGCGCCTTG.1\tAGAGCGACAATGAAAC.1\tAGAGCGACATCTGGTA.1\tAGAGCGACATTTGCCC.1\tAGAGCGAGTACTCTCC.1\tAGAGCGAGTAGGCATG.1\tAGAGCGAGTGGAAAGA.1\tAGAGCTTAGTGCCATT.1\tAGAGCTTAGTGTACGG.1\tAGAGCTTCATTATCTC.1\tAGAGCTTGTCGGCTCA.1\tAGAGCTTGTGCGAAAC.1\tAGAGCTTTCAATCACG.1\tAGAGCTTTCTGCTGTC.1\tAGAGTGGAGCGGATCA.1\tAGAGTGGCACGGACAA.1\tAGAGTGGCATCACCCT.1\tAGAGTGGGTCATACTG.1\tAGAGTGGGTCTTCGTC.1\tAGAGTGGTCAACGAAA.1\tAGAGTGGTCTGAGTGT.1\tAGAGTGGTCTTGTATC.1\tAGATCTGAGTAGGCCA.1\tAGATCTGCAGTCAGCC.1\tAGATCTGCATAGAAAC.1\tAGATCTGGTACAGCAG.1\tAGATCTGGTCGGGTCT.1\tAGATCTGGTCTCTTTA.1\tAGATCTGGTGCACCAC.1\tAGATCTGGTGGTTTCA.1\tAGATCTGGTTTCGCTC.1\tAGATCTGTCAGAGCTT.1\tAGATCTGTCCTGCTTG.1\tAGATCTGTCGGGAGTA.1\tAGATCTGTCTTTCCTC.1\tAGATTGCAGAGCTATA.1\tAGATTGCAGCTAACTC.1\tAGATTGCAGTTGCAGG.1\tAGATTGCCACAGACAG.1\tAGATTGCCATCATCCC.1\tAGATTGCCATCCGCGA.1\tAGATTGCGTAGCTGCC.1\tAGATTGCGTCCGAACC.1\tAGATTGCTCAATCACG.1\tAGATTGCTCACGGTTA.1\tAGATTGCTCAGCTCGG.1\tAGATTGCTCCCGACTT.1\tAGATTGCTCCTTCAAT.1\tAGATTGCTCTCGCTTG.1\tAGATTGCTCTGATTCT.1\tAGCAGCCAGGAGCGTT.1\tAGCAGCCAGTTAGCGG.1\tAGCAGCCCAAACTGTC.1\tAGCAGCCCAACGCACC.1\tAGCAGCCCAGATGGCA.1\tAGCAGCCCAGGTCCAC.1\tAGCAGCCGTAAGCACG.1\tAGCAGCCGTTGCGTTA.1\tAGCAGCCTCAGTCAGT.1\tAGCAGCCTCATACGGT.1\tAGCAGCCTCCACTGGG.1\tAGCAGCCTCCAGGGCT.1\tAGCAGCCTCGTAGGTT.1\tAGCATACAGACCGGAT.1\tAGCATACAGGAATTAC.1\tAGCATACAGGAGCGAG.1\tAGCATACAGGCATTGG.1\tAGCATACAGTTAGCGG.1\tAGCATACCAGTATCTG.1\tAGCATACCATCAGTCA.1\tAGCATACGTAAGTGTA.1\tAGCATACGTGGTCCGT.1\tAGCATACGTTGACGTT.1\tAGCATACGTTGATTGC.1\tAGCATACTCAATCACG.1\tAGCCTAAAGCTACCTA.1\tAGCCTAAAGGGCATGT.1\tAGCCTAAAGTCCAGGA.1\tAGCCTAAAGTGGTAAT.1\tAGCCTAACAATAGAGT.1\tAGCCTAACACATCCGG.1\tAGCCTAACACCACGTG.1\tAGCCTAACAGATAATG.1\tAGCCTAACATCAGTAC.1\tAGCCTAACATGTTCCC.1\tAGCCTAAGTGGGTCAA.1\tAGCCTAATCACGCGGT.1\tAGCCTAATCATCATTC.1\tAGCCTAATCGAGAGCA.1\tAGCCTAATCTTCCTTC.1\tAGCGGTCAGATCCCAT.1\tAGCGGTCAGCTGATAA.1\tAGCGGTCAGGAGTACC.1\tAGCGGTCAGGCTCAGA.1\tAGCGGTCAGGGAGTAA.1\tAGCGGTCAGTGAAGAG.1\tAGCGGTCCAAAGCAAT.1\tAGCGGTCTCACATACG.1\tAGCGGTCTCACCCTCA.1\tAGCGTATAGATGGGTC.1\tAGCGTATAGCCCAGCT.1\tAGCGTATCACTTCTGC.1\tAGCGTATGTGACGGTA.1\tAGCGTATTCAGCGATT.1\tAGCGTCGAGACTAAGT.1\tAGCGTCGGTACCGTAT.1\tAGCGTCGTCGGTGTCG.1\tAGCTCCTAGACCACGA.1\tAGCTCCTAGAGACGAA.1\tAGCTCCTAGGCTCTTA.1\tAGCTCCTAGTACGACG.1\tAGCTCCTCAACTGGCC.1\tAGCTCCTTCACCTTAT.1\tAGCTCCTTCTGAAAGA.1\tAGCTCCTTCTGATTCT.1\tAGCTCTCAGCAATATG.1\tAGCTCTCCAAGGTGTG.1\tAGCTCTCCACGGTGTC.1\tAGCTCTCCATGGTTGT.1\tAGCTCTCGTGGTAACG.1\tAGCTCTCTCCAAATGC.1\tAGCTCTCTCCCACTTG.1\tAGCTCTCTCGTGGACC.1\tAGCTCTCTCTTGTACT.1\tAGCTTGAAGCGTTCCG.1\tAGCTTGAAGTGCGTGA.1\tAGCTTGAGTCCCGACA.1\tAGCTTGAGTGAGGCTA.1\tAGCTTGAGTTCCGGCA.1\tAGCTTGAGTTCTGTTT.1\tAGCTTGATCCTCAATT.1\tAGCTTGATCTTTCCTC.1\tAGGCCACCAAGTTGTC.1\tAGGCCACCATGTAAGA.1\tAGGCCACGTCCCTTGT.1\tAGGCCACGTCCGAATT.1\tAGGCCACGTCGTGGCT.1\tAGGCCACGTTCGCTAA.1\tAGGCCACTCGTCGTTC.1\tAGGCCACTCGTGGACC.1\tAGGCCGTAGAGTAATC.1\tAGGCCGTAGCCTTGAT.1\tAGGCCGTAGGTGCTAG.1\tAGGCCGTGTACCGCTG.1\tAGGCCGTTCAGGCAAG.1\tAGGCCGTTCGTTACGA.1\tAGGGAGTAGATCACGG.1\tAGGGAGTAGCGGATCA.1\tAGGGAGTAGGCTAGGT.1\tAGGGAGTAGTCCCACG.1\tAGGGAGTCACGGCTAC.1\tAGGGAGTGTAGAAAGG.1\tAGGGAGTGTAGCGCTC.1\tAGGGAGTGTGGAAAGA.1\tAGGGAGTGTTACGTCA.1\tAGGGAGTTCACGACTA.1\tAGGGAGTTCAGTCCCT.1\tAGGGAGTTCTGTTGAG.1\tAGGGATGAGCCTCGTG.1\tAGGGATGAGGTGACCA.1\tAGGGATGCAAAGGAAG.1\tAGGGATGCAAGCCATT.1\tAGGGATGCACATCCGG.1\tAGGGATGCAGGTCGTC.1\tAGGGATGCATGCCCGA.1\tAGGGATGGTAAGTAGT.1\tAGGGATGGTGATGTGG.1\tAGGGATGTCAACGGGA.1\tAGGGTGAAGGAGCGAG.1\tAGGGTGACATTGTGCA.1\tAGGGTGAGTAGGGACT.1\tAGGGTGAGTCGGCATC.1\tAGGGTGATCAACTCTT.1\tAGGGTGATCGGTCTAA.1\tAGGTCATAGAATTCCC.1\tAGGTCATAGAGGACGG.1\tAGGTCATAGCGTTGCC.1\tAGGTCATCAAGGCTCC.1\tAGGTCATCAGACAAAT.1\tAGGTCATCAGCTTCGG.1\tAGGTCATCAGGACCCT.1\tAGGTCATGTGTGACCC.1\tAGGTCATGTTGTCGCG.1\tAGGTCATTCAATCACG.1\tAGGTCATTCTGCAAGT.1\tAGGTCCGAGCAGGTCA.1\tAGGTCCGCACAGGTTT.1\tAGGTCCGCACGTAAGG.1\tAGGTCCGGTTTGGGCC.1\tAGGTCCGTCAATACCG.1\tAGGTCCGTCCTGCAGG.1\tAGTAGTCAGTTTAGGA.1\tAGTAGTCCAAACTGTC.1\tAGTAGTCGTAAGTAGT.1\tAGTAGTCTCAACTCTT.1\tAGTAGTCTCGCCTGAG.1\tAGTAGTCTCTGTCCGT.1\tAGTCTTTAGACTGGGT.1\tAGTCTTTCAATCCAAC.1\tAGTCTTTGTCCCGACA.1\tAGTCTTTGTGAAAGAG.1\tAGTCTTTTCCTGTACC.1\tAGTGAGGAGCGTCTAT.1\tAGTGAGGAGCTGTCTA.1\tAGTGAGGCACCTCGGA.1\tAGTGAGGCAGTCAGAG.1\tAGTGAGGGTTAAGGGC.1\tAGTGAGGGTTATCCGA.1\tAGTGAGGTCCGTAGTA.1\tAGTGAGGTCCTTTCGG.1\tAGTGAGGTCGCCAAAT.1\tAGTGGGAAGGGAAACA.1\tAGTGGGACAAAGTCAA.1\tAGTGGGAGTAGCCTAT.1\tAGTGGGAGTATAAACG.1\tAGTGGGAGTCCTCCAT.1\tAGTGGGAGTCTGCCAG.1\tAGTGGGATCAAAGTAG.1\tAGTGTCAAGAATGTTG.1\tAGTGTCACAAGGACTG.1\tAGTGTCACAATGAATG.1\tAGTGTCACACACTGCG.1\tAGTGTCACAGGACGTA.1\tAGTGTCAGTAAGAGAG.1\tAGTGTCAGTCGGCACT.1\tAGTGTCAGTCTAGAGG.1\tAGTGTCAGTTCAGACT.1\tAGTGTCATCTACTATC.1\tAGTTGGTAGGGTGTGT.1\tAGTTGGTAGTAATCCC.1\tAGTTGGTCAATACGCT.1\tAGTTGGTGTCGAGATG.1\tAGTTGGTGTCTTCTCG.1\tAGTTGGTGTTAGGGTG.1\tAGTTGGTGTTCCATGA.1\tATAACGCAGGAATCGC.1\tATAACGCAGTCCATAC.1\tATAACGCAGTGCAAGC.1\tATAACGCAGTGGTAAT.1\tATAACGCCACGAAACG.1\tATAACGCCACTGCCAG.1\tATAACGCGTATTCGTG.1\tATAACGCGTCATATCG.1\tATAACGCTCGATAGAA.1\tATAACGCTCTGGGCCA.1\tATAAGAGAGCCAACAG.1\tATAAGAGAGGAATTAC.1\tATAAGAGCAACGATCT.1\tATAAGAGCATCGGGTC.1\tATAAGAGGTAAACACA.1\tATAAGAGGTATCACCA.1\tATAAGAGTCCAGAGGA.1\tATAAGAGTCCATTCTA.1\tATAAGAGTCCTGCTTG.1\tATAAGAGTCGCCAAAT.1\tATAAGAGTCGCCGTGA.1\tATAGACCAGATGTGTA.1\tATAGACCAGATTACCC.1\tATAGACCAGGAATTAC.1\tATAGACCAGGAGTTGC.1\tATAGACCCAATGGATA.1\tATAGACCCACCCTATC.1\tATAGACCCACCGAAAG.1\tATAGACCCAGACACTT.1\tATAGACCCAGTATGCT.1\tATAGACCCATGTAGTC.1\tATAGACCGTCCTGCTT.1\tATAGACCGTTAAGAAC.1\tATAGACCGTTCCGGCA.1\tATAGACCTCAGCTGGC.1\tATAGACCTCTGGCGTG.1\tATCACGAAGAAGAAGC.1\tATCACGAAGATAGCAT.1\tATCACGAAGGTGATTA.1\tATCACGAAGTACGCCC.1\tATCACGACAAGCCGCT.1\tATCACGACAGCTCGAC.1\tATCACGACAGTGACAG.1\tATCACGAGTACATGTC.1\tATCACGAGTGACAAAT.1\tATCACGAGTGGTTTCA.1\tATCACGATCCTAGAAC.1\tATCATCTAGTTACGGG.1\tATCATCTCAGGTGGAT.1\tATCATCTCATAACCTG.1\tATCATCTTCAGCTCTC.1\tATCATCTTCCTAAGTG.1\tATCATCTTCGGTGTCG.1\tATCATGGAGGCACATG.1\tATCATGGAGTGGAGTC.1\tATCATGGAGTTGAGTA.1\tATCATGGCACACATGT.1\tATCATGGCACACCGCA.1\tATCATGGGTGCGGTAA.1\tATCATGGTCGTTTAGG.1\tATCCACCAGAGTAAGG.1\tATCCACCAGGGTGTGT.1\tATCCACCAGGGTTTCT.1\tATCCACCAGTGGGCTA.1\tATCCACCCAACACCTA.1\tATCCACCCACGAGGTA.1\tATCCACCGTTGAGTTC.1\tATCCACCTCAGCTGGC.1\tATCCACCTCCAATGGT.1\tATCCGAAAGATCCCGC.1\tATCCGAAAGCGTTCCG.1\tATCCGAAAGGGATGGG.1\tATCCGAACAAACGTGG.1\tATCCGAACAAAGGAAG.1\tATCCGAACATCACGAT.1\tATCCGAAGTGCCTGCA.1\tATCCGAAGTTCCAACA.1\tATCCGAATCCAAAGTC.1\tATCCGAATCCCGGATG.1\tATCCGAATCGGAAACG.1\tATCCGAATCTGGTATG.1\tATCGAGTAGACTAGAT.1\tATCGAGTAGATCGGGT.1\tATCGAGTAGGATGGAA.1\tATCGAGTCAAGCGATG.1\tATCGAGTGTCCAGTTA.1\tATCGAGTTCGTGGTCG.1\tATCGAGTTCTGGAGCC.1\tATCTACTAGTCTTGCA.1\tATCTACTCAACCGCCA.1\tATCTACTCAGACAAGC.1\tATCTACTCAGGGTACA.1\tATCTACTCATAACCTG.1\tATCTACTCATGAACCT.1\tATCTACTGTAAAGTCA.1\tATCTACTTCCAAACAC.1\tATCTACTTCCAACCAA.1\tATCTACTTCTCCGGTT.1\tATCTGCCCACTTGGAT.1\tATCTGCCCAGACAGGT.1\tATCTGCCCAGTATGCT.1\tATCTGCCGTACTTCTT.1\tATCTGCCGTTACGACT.1\tATCTGCCGTTCTGGTA.1\tATCTGCCTCAGTGTTG.1\tATCTGCCTCCTAGTGA.1\tATCTGCCTCGCCATAA.1\tATGAGGGCACATTCGA.1\tATGAGGGGTAAATGTG.1\tATGCGATAGACTCGGA.1\tATGCGATAGAGCTATA.1\tATGCGATAGAGTACCG.1\tATGCGATCACCACCAG.1\tATGCGATGTCGACTGC.1\tATGCGATGTCTTGCGG.1\tATGCGATTCACCGGGT.1\tATGCGATTCTCAACTT.1\tATGCGATTCTGTTTGT.1\tATGCGATTCTTCGAGA.1\tATGGGAGAGTACGACG.1\tATGGGAGCATCTATGG.1\tATGGGAGGTAAGCACG.1\tATGGGAGGTGCTTCTC.1\tATGGGAGTCCTTTCTC.1\tATGGGAGTCTACCTGC.1\tATGGGAGTCTATCCTA.1\tATGTGTGCAAGCGATG.1\tATGTGTGCAAGTTCTG.1\tATGTGTGCACACTGCG.1\tATGTGTGGTGACGGTA.1\tATGTGTGGTTAAGTAG.1\tATGTGTGGTTCCACAA.1\tATTACTCCACATGGGA.1\tATTACTCCATGCTGGC.1\tATTACTCGTCCCTTGT.1\tATTACTCGTGAGCGAT.1\tATTACTCGTTACCGAT.1\tATTACTCTCCTAGGGC.1\tATTATCCAGCATCATC.1\tATTATCCAGGCATGGT.1\tATTATCCCACCAGCAC.1\tATTATCCCAGACGCCT.1\tATTATCCCAGGCAGTA.1\tATTATCCGTGCACGAA.1\tATTATCCTCAATCTCT.1\tATTATCCTCACGCATA.1\tATTATCCTCGGTGTTA.1\tATTCTACAGTGGACGT.1\tATTCTACGTCGGGTCT.1\tATTCTACTCCGTTGTC.1\tATTCTACTCGCAAGCC.1\tATTCTACTCGTGGACC.1\tATTGGACCAAGCCTAT.1\tATTGGACCAAGGACTG.1\tATTGGACCAGACAAAT.1\tATTGGACGTGGTAACG.1\tATTGGACTCTAACTCT.1\tATTGGTGAGCGTTTAC.1\tATTGGTGAGGCATTGG.1\tATTGGTGCACATCTTT.1\tATTGGTGCATTATCTC.1\tATTGGTGGTTCAGGCC.1\tATTGGTGTCGGCATCG.1\tATTTCTGAGAATTCCC.1\tATTTCTGAGAGAACAG.1\tATTTCTGAGAGGTACC.1\tATTTCTGAGGACGAAA.1\tATTTCTGAGGAGTTGC.1\tATTTCTGAGGGTGTGT.1\tATTTCTGAGTCAAGGC.1\tATTTCTGCAATAGAGT.1\tATTTCTGCACGTCTCT.1\tATTTCTGGTCCCTACT.1\tATTTCTGGTGCGATAG.1\tATTTCTGGTTCTGTTT.1\tCAACCAAAGATCACGG.1\tCAACCAAAGCAGATCG.1\tCAACCAAAGCGATGAC.1\tCAACCAACATCGGTTA.1\tCAACCAAGTTTGGGCC.1\tCAACCAATCATGCATG.1\tCAACCAATCCGCGCAA.1\tCAACCAATCCTAAGTG.1\tCAACCAATCGCATGGC.1\tCAACCTCAGAAGATTC.1\tCAACCTCAGAGCTTCT.1\tCAACCTCAGATACACA.1\tCAACCTCAGGGTGTTG.1\tCAACCTCCAAACGCGA.1\tCAACCTCCAAGTCATC.1\tCAACCTCCACGTCAGC.1\tCAACCTCCAGTGACAG.1\tCAACCTCGTTCGCGAC.1\tCAACCTCTCAATCACG.1\tCAACCTCTCACGCGGT.1\tCAACCTCTCCTTGCCA.1\tCAACCTCTCTTCATGT.1\tCAACTAGAGCCCAATT.1\tCAACTAGCACCAGTTA.1\tCAACTAGCAGCTGGCT.1\tCAACTAGGTATTCGTG.1\tCAACTAGGTGTGCGTC.1\tCAACTAGGTTCTGGTA.1\tCAACTAGTCAAGCCTA.1\tCAACTAGTCATTGCCC.1\tCAAGAAAAGAATGTTG.1\tCAAGAAAAGACGCACA.1\tCAAGAAAAGAGGTTGC.1\tCAAGAAAAGCTATGCT.1\tCAAGAAACAAGCGTAG.1\tCAAGAAAGTGCACCAC.1\tCAAGATCAGAGTACAT.1\tCAAGATCAGGATCGCA.1\tCAAGATCAGGCATGGT.1\tCAAGATCAGTGAATTG.1\tCAAGATCAGTGGTAAT.1\tCAAGATCCAACTGCTA.1\tCAAGATCCAAGTAATG.1\tCAAGATCCACCGGAAA.1\tCAAGATCGTAAATACG.1\tCAAGATCGTGCAACTT.1\tCAAGGCCAGAGTAATC.1\tCAAGGCCCAGCTGCTG.1\tCAAGGCCTCATATCGG.1\tCAAGTTGAGAGGTTAT.1\tCAAGTTGCAACTGCTA.1\tCAAGTTGCATGCCCGA.1\tCAAGTTGGTACCAGTT.1\tCAAGTTGGTTGGTGGA.1\tCAAGTTGGTTGGTTTG.1\tCAAGTTGTCACATGCA.1\tCAAGTTGTCACCTCGT.1\tCACAAACCACATGACT.1\tCACAAACGTAAGAGAG.1\tCACAAACGTCTGATTG.1\tCACAAACTCAGCGACC.1\tCACAAACTCAGCTTAG.1\tCACAAACTCCGTCATC.1\tCACAAACTCTGCTTGC.1\tCACAAACTCTGTGCAA.1\tCACACAAAGCCCAATT.1\tCACACAAAGGCTCAGA.1\tCACACAAAGGTCGGAT.1\tCACACAAAGTGTTAGA.1\tCACACAAAGTTCGATC.1\tCACACAAGTTTAGGAA.1\tCACACAATCGGCGGTT.1\tCACACCTCAGACACTT.1\tCACACCTCAGCCAATT.1\tCACACCTCAGGATTGG.1\tCACACCTCAGGCTCAC.1\tCACACCTCAGTGGAGT.1\tCACACCTGTACCGTTA.1\tCACACCTGTAGAAGGA.1\tCACACCTTCAACACCA.1\tCACACCTTCGCCCTTA.1\tCACACCTTCTGTCTCG.1\tCACACTCAGAAGCCCA.1\tCACACTCAGTGGTCCC.1\tCACACTCCACTATCTT.1\tCACACTCTCACGACTA.1\tCACACTCTCTTCAACT.1\tCACAGGCAGACAGACC.1\tCACAGGCCAACACCTA.1\tCACAGGCCAACTGCGC.1\tCACAGGCCACCCATTC.1\tCACAGGCCATCACGAT.1\tCACAGGCCATCGGAAG.1\tCACAGGCGTACTTGAC.1\tCACAGGCGTCCCTACT.1\tCACAGTAAGAAGAAGC.1\tCACAGTAAGATCTGCT.1\tCACAGTAAGATGCCTT.1\tCACAGTAAGCCGGTAA.1\tCACAGTAAGGTGGGTT.

In [6]:
df = pd.read_csv("GSM4089151_P1_gene_cell_exprs_table.txt", sep ="\t")

In [7]:
df

,Gene_ID,Symbol,AAACCTGAGAGCTATA.1,AAACCTGAGTGTTTGC.1,AAACCTGCAGTCAGCC.1,AAACCTGGTACATGTC.1,AAACCTGGTCGGCATC.1,AAACCTGGTGCAGACA.1,AAACCTGTCATTCACT.1,AAACCTGTCTTGAGGT.1,...,TTTGGTTAGTGTACTC.1,TTTGGTTCACATCTTT.1,TTTGGTTCATTACCTT.1,TTTGGTTGTCCGACGT.1,TTTGGTTGTGAAATCA.1,TTTGTCAAGCTAGTTC.1,TTTGTCACAATCCAAC.1,TTTGTCACACATGTGT.1,TTTGTCACAGTCACTA.1,TTTGTCAGTGTCAATC.1
0,ENSG00000000003,TSPAN6,1,0,0,1,0,2,1,0,...,0,1,0,0,1,0,0,0,1,0
1,ENSG00000000419,DPM1,0,1,2,0,1,0,0,0,...,0,0,1,0,0,1,1,0,0,0
2,ENSG00000000457,SCYL3,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,ENSG00000000460,C1orf112,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ENSG00000000938,FGR,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23423,ENSG00000283071,RP11-736N17.11,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23424,ENSG00000283073,RP11-834C11.15,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23425,ENSG00000283078,RP11-11M20.4,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
23426,ENSG00000283083,RP11-61G19.2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23427,ENSG00000283103,LLNLR-245B6.1,0,0,2,0,0,0,1,0,...,0,3,0,5,1,2,6,0,1,1

In [8]:
df.head()

,Gene_ID,Symbol,AAACCTGAGAGCTATA.1,AAACCTGAGTGTTTGC.1,AAACCTGCAGTCAGCC.1,AAACCTGGTACATGTC.1,AAACCTGGTCGGCATC.1,AAACCTGGTGCAGACA.1,AAACCTGTCATTCACT.1,AAACCTGTCTTGAGGT.1,...,TTTGGTTAGTGTACTC.1,TTTGGTTCACATCTTT.1,TTTGGTTCATTACCTT.1,TTTGGTTGTCCGACGT.1,TTTGGTTGTGAAATCA.1,TTTGTCAAGCTAGTTC.1,TTTGTCACAATCCAAC.1,TTTGTCACACATGTGT.1,TTTGTCACAGTCACTA.1,TTTGTCAGTGTCAATC.1
0,ENSG00000000003,TSPAN6,1,0,0,1,0,2,1,0,...,0,1,0,0,1,0,0,0,1,0
1,ENSG00000000419,DPM1,0,1,2,0,1,0,0,0,...,0,0,1,0,0,1,1,0,0,0
2,ENSG00000000457,SCYL3,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,ENSG00000000460,C1orf112,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ENSG00000000938,FGR,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
df.describe()

,AAACCTGAGAGCTATA.1,AAACCTGAGTGTTTGC.1,AAACCTGCAGTCAGCC.1,AAACCTGGTACATGTC.1,AAACCTGGTCGGCATC.1,AAACCTGGTGCAGACA.1,AAACCTGTCATTCACT.1,AAACCTGTCTTGAGGT.1,AAACGGGAGAGCCTAG.1,AAACGGGCAATAAGCA.1,...,TTTGGTTAGTGTACTC.1,TTTGGTTCACATCTTT.1,TTTGGTTCATTACCTT.1,TTTGGTTGTCCGACGT.1,TTTGGTTGTGAAATCA.1,TTTGTCAAGCTAGTTC.1,TTTGTCACAATCCAAC.1,TTTGTCACACATGTGT.1,TTTGTCACAGTCACTA.1,TTTGTCAGTGTCAATC.1
count,23428.000000,23428.000000,23428.000000,23428.000000,23428.000000,23428.000000,23428.000000,23428.000000,23428.000000,23428.000000,...,23428.000000,23428.000000,23428.000000,23428.000000,23428.000000,23428.000000,23428.000000,23428.000000,23428.000000,23428.000000
mean,0.369472,0.503372,1.367466,0.595569,0.686401,0.573673,0.994750,0.809288,0.960176,1.503244,...,0.374808,1.891156,0.548660,1.800581,0.541873,0.478103,1.799300,0.289781,0.999659,0.651016
std,3.445927,5.085988,16.715392,7.122545,6.883213,5.779606,9.758448,9.543255,10.138735,17.669981,...,3.854859,22.915493,6.163741,20.888016,7.002734,7.360489,21.350185,3.235995,13.858289,7.328200
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,128.000000,207.000000,1790.000000,462.000000,257.000000,200.000000,382.000000,428.000000,487.000000,828.000000,...,210.000000,1225.000000,693.000000,1300.000000,622.000000,800.000000,1110.000000,279.000000,1405.000000,308.000000

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23428 entries, 0 to 23427
Columns: 3963 entries, Gene_ID to TTTGTCAGTGTCAATC.1
dtypes: int64(3961), object(2)
memory usage: 708.4+ MB

In [12]:
df.set_index("Symbol" , inplace= True)

In [13]:
df

,Gene_ID,AAACCTGAGAGCTATA.1,AAACCTGAGTGTTTGC.1,AAACCTGCAGTCAGCC.1,AAACCTGGTACATGTC.1,AAACCTGGTCGGCATC.1,AAACCTGGTGCAGACA.1,AAACCTGTCATTCACT.1,AAACCTGTCTTGAGGT.1,AAACGGGAGAGCCTAG.1,...,TTTGGTTAGTGTACTC.1,TTTGGTTCACATCTTT.1,TTTGGTTCATTACCTT.1,TTTGGTTGTCCGACGT.1,TTTGGTTGTGAAATCA.1,TTTGTCAAGCTAGTTC.1,TTTGTCACAATCCAAC.1,TTTGTCACACATGTGT.1,TTTGTCACAGTCACTA.1,TTTGTCAGTGTCAATC.1
Symbol,,,,,,,,,,,,,,,,,,,,,
TSPAN6,ENSG00000000003,1,0,0,1,0,2,1,0,2,...,0,1,0,0,1,0,0,0,1,0
DPM1,ENSG00000000419,0,1,2,0,1,0,0,0,0,...,0,0,1,0,0,1,1,0,0,0
SCYL3,ENSG00000000457,0,1,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
C1orf112,ENSG00000000460,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FGR,ENSG00000000938,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RP11-736N17.11,ENSG00000283071,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
RP11-834C11.15,ENSG00000283073,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
RP11-11M20.4,ENSG00000283078,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
RP11-61G19.2,ENSG00000283083,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
LLNLR-245B6.1,ENSG00000283103,0,0,2,0,0,0,1,0,5,...,0,3,0,5,1,2,6,0,1,1

In [22]:
df["Gene_ID"] = df["Gene_ID"].str.replace("Gene_ID", " ", regex=True)

In [21]:
df

,Gene_ID,AAACCTGAGAGCTATA.1,AAACCTGAGTGTTTGC.1,AAACCTGCAGTCAGCC.1,AAACCTGGTACATGTC.1,AAACCTGGTCGGCATC.1,AAACCTGGTGCAGACA.1,AAACCTGTCATTCACT.1,AAACCTGTCTTGAGGT.1,AAACGGGAGAGCCTAG.1,...,TTTGGTTAGTGTACTC.1,TTTGGTTCACATCTTT.1,TTTGGTTCATTACCTT.1,TTTGGTTGTCCGACGT.1,TTTGGTTGTGAAATCA.1,TTTGTCAAGCTAGTTC.1,TTTGTCACAATCCAAC.1,TTTGTCACACATGTGT.1,TTTGTCACAGTCACTA.1,TTTGTCAGTGTCAATC.1
Symbol,,,,,,,,,,,,,,,,,,,,,
TSPAN6,,1,0,0,1,0,2,1,0,2,...,0,1,0,0,1,0,0,0,1,0
DPM1,,0,1,2,0,1,0,0,0,0,...,0,0,1,0,0,1,1,0,0,0
SCYL3,,0,1,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
C1orf112,,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FGR,,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
RP11-736N17.11,,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
RP11-834C11.15,,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
RP11-11M20.4,,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
RP11-61G19.2,,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
LLNLR-245B6.1,,0,0,2,0,0,0,1,0,5,...,0,3,0,5,1,2,6,0,1,1

In [33]:
df.to_csv("Parsed_data_matrix",index = False)